description: >
  This command echos "Hello World" using file inclusion.
# What will this command do?
# Descriptions should be short, simple, and clear.
parameters:
  config-dir:
    type: string
    default: ".circleci/config"
    description: "Hello to whom?"
steps:
  - run:
      name: compare md5sum
      command: << include(scripts/config-check.sh) >>
      environment:
        CONFIG_DIR: << parameters.config-dir >>
